### PR TITLE
adding subpages and changing the about page

### PR DESCRIPTION
**Pull request by sanpinrin1**
abt-consult.hbs is consultant subpage
abt-DS.hbs is Detailing and Samples subpage
abthits.hbs is Health Information Technology System
abt-HDIS.hbs is Health Data Integration Services

### CODE REVIEW

**Comment by sanpinrin1** [comment]
@skagels-hitslab Hello Scott I am not being able to link the subpages to their respective links on the about page. I will need some help in that

**Comment by skagels-hitslab** [comment]
@sanpinrin1 For creating routes for sub pages see hitslabs.js. Follow the pattern used for GET /about on line 71:

app.get("/about",   onAboutPage);

**Comment by sanpinrin1** [comment]
The subpages are up

**Comment by skagels-hitslab** [comment]
Hi Mohamed,

Please make sure that you are a little more careful with testing and proofreading content changes against the details of issue #69. Please review points below. Please ask questions if you are unsure why something is done a certain way.

- hitslabs.js
-- A couple of calls to render pages are missing an important context property ( hide_aux_panel: true ). This context property is set to hide advertisement from displaying on specific pages. Please review your changes and restore hide_aux_panel properties that were removed. 
-- Page Routes :

    app.get("/abtconsult", onAbtConsultPage);
    app.get("/abtDS", onAbtDsPage);
    app.get("/abtHDIS", onAbtHdisPage);
    app.get("/abthits", onAbthitsPage);

Please do not use abbreviations, example: Abt for About. Just use About. The use of acronyms is OK. I would like to see the following for paths and function names for the routes:
-- path: /abtconsult > /about_Consultancy, function: onAbtConsultPage > onAboutConsultancyPage
-- path: /abtDS > /about_DS, function abtDS > onAboutDSPage
-- path: /abtHDIS > /about_HDIS, function onAbtHdisPage > onAboutHDISPage
-- path: /abthits > /about_HITS, function: onAbthitsPage > onAboutHITSPage
- about.hbs - About Page (/about)
-- Please proofread sub page link display names paying attention to proper capitalization and  remove periods (".") at the end of each link per Issue #69 details
-- All the links for the sub pages are broken. Fix anchor src values and test to make sure they work.
-- Please make correction in Our Story section per Issue #69 details.
-- Please add December 2016 milestone to the Milestones section of the About page per Issue #69 details

Thanks,
Scott

**Comment by sanpinrin1** [comment]
Hello scott

I would be more careful from now on but you said that the links were broken when i tested the links on my linux system they were working.
You said to make corrections in our story section per issue # 69. I didn't understand that.

Thank you

Sent from my iPhone

On Dec 9, 2016, at 1:13 AM, Scott Kagels <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mohamed,

Please make sure that you are a little more careful with testing and proofreading content changes against the details of issue #69<https://github.com/Hitslabs/hitslabs/issues/69>. Please review points below. Please ask questions if you are unsure why something is done a certain way.

  *   hitslabs.js
-- A couple of calls to render pages are missing an important context property ( hide_aux_panel: true ). This context property is set to hide advertisement from displaying on specific pages. Please review your changes and restore hide_aux_panel properties that were removed.
-- Page Routes :

app.get("/abtconsult", onAbtConsultPage);
app.get("/abtDS", onAbtDsPage);
app.get("/abtHDIS", onAbtHdisPage);
app.get("/abthits", onAbthitsPage);

Please do not use abbreviations, example: Abt for About. Just use About. The use of acronyms is OK. I would like to see the following for paths and function names for the routes:
-- path: /abtconsult > /about_Consultancy, function: onAbtConsultPage > onAboutConsultancyPage
-- path: /abtDS > /about_DS, function abtDS > onAboutDSPage
-- path: /abtHDIS > /about_HDIS, function onAbtHdisPage > onAboutHDISPage
-- path: /abthits > /about_HITS, function: onAbthitsPage > onAboutHITSPage

  *   about.hbs - About Page (/about)
-- Please proofread sub page link display names paying attention to proper capitalization and remove periods (".") at the end of each link per Issue #69<https://github.com/Hitslabs/hitslabs/issues/69> details
-- All the links for the sub pages are broken. Fix anchor src values and test to make sure they work.
-- Please make correction in Our Story section per Issue #69<https://github.com/Hitslabs/hitslabs/issues/69> details.
-- Please add December 2016 milestone to the Milestones section of the About page per Issue #69<https://github.com/Hitslabs/hitslabs/issues/69> details

Thanks,
Scott

-

**Comment by skagels-hitslab** [comment]
Mohamed,

On the about page, the urls for the links to the sub pages did not match up with the sub page routes set in hitslab.js so I don't understand how they could have worked for you. I believe a couple were just pointing to the home page.

With regards to Our Story corrections, please review Paul's description of work to be done in issue #69. There is a content correction to be made in the Our Story section: Change "noticed" to "determined".

Sent from my iPhone
617.970.5231

**Comment by sanpinrin1** [comment]
I have changed the names of the path to the subpages.
I added the hide_aux_panel properties that were missing.
I reviewed the subpages to make sure that they match issue #69 detail.
On the about page i made correction to the our story and milestone section.
sorry for the delays

**Pull request merged**
